### ISSUE TITLE
[计划] 模块：GameruleLock

### ISSUE THREAD

**Issue by katorly** [katorlys/StarlinUtils#14]
### Suggestion

配置中可设定在每次开服时，服务器加载完毕后自动检测设定的gamerule是否为设定的值，若不是，则设为设定值。配置文件参考：
```yml
gamerules:
  keepInventory:
    value: true
    worlds: *
  randomTickSpeed:
    value: 20
    worlds: world, world_the_end
```

### Reason

来自某玩家：  
<img width="423" src="https://user-images.githubusercontent.com/70022443/226376991-5f605360-bf20-4686-8dca-31b8a48e79be.png">  

**我：** 可能是版本迭代的时候，一开始没加Multiverse-Core，就是全局的gamerule死亡不掉了；后来加了多世界插件，多世界插件不知道为什么改动了原本的gamerule，太匆忙没发现，忘记对每个世界都设了  
哦对了，貌似CoreProtect不支持保存玩家背包，即使掉落物品的数据都只有物品名称，连个附魔都不显示  

**玩家：** 你 吗？

### Other

需要检测服务器是否安装了Multiverse-Core。若有，则用其API对gamerule进行设置；若无，则用Spigot提供的API进行全局gamerule设置。
